# Generated by Django 2.0.1 on 2018-01-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examScore', models.IntegerField(help_text='Total score of the exam', max_length=200)),
                ('attemtps', models.IntegerField(help_text='Total of exam trials', max_length=200)),
            ],
        ),
    ]
