# Generated by Django 2.0.1 on 2018-01-19 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isAdmin', models.BooleanField(default=True)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='company.Company')),
                ('examID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exam', to='modules.Modules')),
                ('modulesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to='modules.Modules')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
