# Generated by Django 2.0.1 on 2018-01-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionReached', models.IntegerField(default=0, help_text='Max session reached')),
            ],
        ),
    ]
