# Generated by Django 2.0.1 on 2018-02-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='sessionReached',
            field=models.IntegerField(default=1, help_text='Max session reached'),
        ),
    ]
