# Generated by Django 2.0.1 on 2018-01-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionNumber', models.IntegerField(help_text='Number of the corresponding session', max_length=30)),
                ('presentationDone', models.BooleanField(default=True)),
                ('docDone', models.BooleanField(default=True)),
                ('slideReached', models.IntegerField(help_text='Last slide reached', max_length=200)),
                ('pageReached', models.IntegerField(help_text='Last document page reached', max_length=200)),
                ('examID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='exam.Exam')),
                ('modulesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='modules.Modules')),
            ],
        ),
    ]
