# Generated by Django 2.0.1 on 2018-01-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='docDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='pageReached',
            field=models.IntegerField(default=0, help_text='Last document page reached', max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='presentationDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='slideReached',
            field=models.IntegerField(default=0, help_text='Last slide reached', max_length=200),
        ),
    ]
