# Generated by Django 2.0.1 on 2018-01-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20180120_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='pageReached',
            field=models.IntegerField(default=0, help_text='Last document page reached'),
        ),
        migrations.AlterField(
            model_name='session',
            name='sessionNumber',
            field=models.IntegerField(help_text='Number of the corresponding session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='slideReached',
            field=models.IntegerField(default=0, help_text='Last slide reached'),
        ),
    ]
