# Generated by Django 2.0.1 on 2018-02-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20180120_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
