# Generated by Django 2.0.1 on 2018-02-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20180228_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
