# Generated by Django 2.0.1 on 2018-03-03 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0005_auto_20180228_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='examID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_id', to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='session',
            name='modulesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_id', to='modules.Modules'),
        ),
    ]
