# Generated by Django 2.0.1 on 2018-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20180303_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='videoDone',
            field=models.BooleanField(default=False),
        ),
    ]
